### Word Embedding Techniques using Embedding Layer in Keras

In [1]:
### Libraries USed Tensorflow> 2.0  and keras

In [6]:
!pip install tensorflow-gpu==2.9.1


     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 511.7/511.7 MB 3.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 89.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.6/42.6 kB 6.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 77.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.8/5.8 MB 102.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 438.7/438.7 kB 37.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.9/4.9 MB 73.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 781.3/781.3 kB 49.0 MB/s eta 0:00:00
  Attempting uninstall: keras
    Found existing installation: keras 2.15.0
    Uninstalling keras-2.15.0:
      Successfully uninstalled keras-2.15.0
  Attempting uninstall: flatbuffers
    Found existing installation: flatbuffers 24.3.25
    Uninstalling flatbuffers-24.3.25:
      Successfully uninstalled flatbuffers-24.3.25
  Attempting uninstall: te

In [3]:
import tensorflow as tf
print(tf.__version__)

2.9.1


In [1]:
##tensorflow >2.0
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good']

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
### Vocabulary size
voc_size=500

#### One Hot Representation

In [7]:
onehot_repr=[one_hot(words,voc_size)for words in sent]
print(onehot_repr)

[[80, 60, 389, 308], [80, 60, 389, 76], [80, 145, 389, 137], [130, 86, 356, 257, 305], [130, 86, 356, 257, 174], [421, 80, 492, 389, 134], [100, 445, 35, 257]]


### Word Embedding Represntation

In [8]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [9]:
import numpy as np

In [10]:
## pre padding
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[  0   0   0   0  80  60 389 308]
 [  0   0   0   0  80  60 389  76]
 [  0   0   0   0  80 145 389 137]
 [  0   0   0 130  86 356 257 305]
 [  0   0   0 130  86 356 257 174]
 [  0   0   0 421  80 492 389 134]
 [  0   0   0   0 100 445  35 257]]


In [ ]:
## 10 feature dimesnions
dim=10


In [11]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [12]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             5000      
                                                                 
Total params: 5000 (19.53 KB)
Trainable params: 5000 (19.53 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [13]:
##'the glass of milk',
embedded_docs[0]

array([  0,   0,   0,   0,  80,  60, 389, 308], dtype=int32)

In [14]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 117ms/step


array([[ 0.00575059,  0.01672821,  0.026559  ,  0.02679614, -0.02905239,
         0.00052174, -0.01100288,  0.02951357,  0.00713109, -0.03509364],
       [ 0.00575059,  0.01672821,  0.026559  ,  0.02679614, -0.02905239,
         0.00052174, -0.01100288,  0.02951357,  0.00713109, -0.03509364],
       [ 0.00575059,  0.01672821,  0.026559  ,  0.02679614, -0.02905239,
         0.00052174, -0.01100288,  0.02951357,  0.00713109, -0.03509364],
       [ 0.00575059,  0.01672821,  0.026559  ,  0.02679614, -0.02905239,
         0.00052174, -0.01100288,  0.02951357,  0.00713109, -0.03509364],
       [-0.02051178,  0.03203272,  0.01078732,  0.04819629, -0.01546429,
        -0.03661992,  0.00399948,  0.01729728, -0.029488  ,  0.00982083],
       [ 0.00034715,  0.00075637,  0.02893672,  0.0314237 , -0.01478295,
        -0.00953148,  0.00310806, -0.0383883 , -0.04538589, -0.02703258],
       [ 0.03669194, -0.00477638,  0.0292452 ,  0.0222153 , -0.01381798,
         0.01703998, -0.01515637,  0.00927008

In [15]:
print(model.predict(embedded_docs))

1/1 [==============================] - 0s 36ms/step
[[[ 5.75058535e-03  1.67282112e-02  2.65589990e-02  2.67961361e-02
   -2.90523898e-02  5.21741807e-04 -1.10028759e-02  2.95135714e-02
    7.13108853e-03 -3.50936428e-02]
  [ 5.75058535e-03  1.67282112e-02  2.65589990e-02  2.67961361e-02
   -2.90523898e-02  5.21741807e-04 -1.10028759e-02  2.95135714e-02
    7.13108853e-03 -3.50936428e-02]
  [ 5.75058535e-03  1.67282112e-02  2.65589990e-02  2.67961361e-02
   -2.90523898e-02  5.21741807e-04 -1.10028759e-02  2.95135714e-02
    7.13108853e-03 -3.50936428e-02]
  [ 5.75058535e-03  1.67282112e-02  2.65589990e-02  2.67961361e-02
   -2.90523898e-02  5.21741807e-04 -1.10028759e-02  2.95135714e-02
    7.13108853e-03 -3.50936428e-02]
  [-2.05117818e-02  3.20327170e-02  1.07873194e-02  4.81962897e-02
   -1.54642947e-02 -3.66199240e-02  3.99948284e-03  1.72972791e-02
   -2.94880029e-02  9.82083008e-03]
  [ 3.47148627e-04  7.56371766e-04  2.89367177e-02  3.14236991e-02
   -1.47829540e-02 -9.53147560e

In [ ]:
embedded_docs[0]

array([   0,    0,    0,    0, 6654,  998, 8966, 1609])

In [ ]:
print(model.predict(embedded_docs)[0])

[[-0.00425554 -0.00159295 -0.04714153  0.04425247 -0.00973954 -0.04325813
   0.04007108 -0.0143286  -0.03659749 -0.02379028]
 [-0.00425554 -0.00159295 -0.04714153  0.04425247 -0.00973954 -0.04325813
   0.04007108 -0.0143286  -0.03659749 -0.02379028]
 [-0.00425554 -0.00159295 -0.04714153  0.04425247 -0.00973954 -0.04325813
   0.04007108 -0.0143286  -0.03659749 -0.02379028]
 [-0.00425554 -0.00159295 -0.04714153  0.04425247 -0.00973954 -0.04325813
   0.04007108 -0.0143286  -0.03659749 -0.02379028]
 [-0.03786323 -0.02628061  0.02974111 -0.03307171  0.0271405   0.00945134
   0.02378127  0.04176904  0.00514941  0.0152082 ]
 [ 0.04834186  0.04388311 -0.02802253 -0.01475487 -0.01212303  0.03762435
  -0.01166249 -0.02141088  0.04654533  0.01537322]
 [ 0.03276015 -0.00637691  0.03907344 -0.01912468  0.02177186 -0.04630325
   0.00800942 -0.03115667 -0.00486455 -0.04843524]
 [-0.04173617  0.03438064  0.02880521 -0.01896455  0.0323303  -0.00109453
  -0.01675171 -0.00941917 -0.03309294 -0.04779492]]